### ISSUE TITLE
Default model options are global

### ISSUE THREAD

**Issue by tkarna** [thetisproject/thetis#109]
It appears that the default model options are in global scope:
```python
from thetis import *
import thetis.options

a = thetis.options.ModelOptions2d()
a.timestepper_options.solver_parameters = {'for': 'bar'}

print('a: {:}'.format(a.timestepper_options.solver_parameters))

b = thetis.options.ModelOptions2d()
print('b: {:}'.format(b.timestepper_options.solver_parameters))
```
Prints
```
a: {'foo': 'bar'}
b: {'foo': 'bar'}
```
Probably not what we want. At least this affects the test suite.

I think this is because we define the default options as trait objects in `attach_paired_options` decorator, rather than a class that should be initiated separately for each instance.

**Comment by wence-** [comment]
Can you try #110?
