### ISSUE TITLE
Issues running tidal_lagoon example

### ISSUE THREAD

**Issue by jhill1** [thetisproject/thetis#133]
(firedrake) jh1889@rheic ~/work/software/firedrake/src/thetis/examples/tidal_barrage $ python lagoon2d.py 
dt = 25
Using time integrator: CrankNicolson
Traceback (most recent call last):
  File "lagoon2d.py", line 88, in <module>
    number_timesteps=5, name="lagoon_1", export_to_hdf5=True)
TypeError: Can't instantiate abstract class LagoonCallback with abstract methods message_str

Up-to-date firedrake and thetis (updated this morning). Let me know if you want any other info.

**Comment by wence-** [comment]
That example needs to be updated to include an implementation of `message_str` in the callback it defines.  You might be able to do:

```
def message_str(self, *args):
    super().message_str(*args)
```

**Comment by jhill1** [comment]
Yep, adding the above function to modules/tools.py (LagoonCallback class) worked. Thanks.

**Comment by thangel** [comment]
Just testing a branch with the fix and will make a pull request shortly

**Comment by thangel** [comment]
Thanks for noticing!

**Comment by thangel** [comment]
Revised the lagoon example. it should be working fine now. Many thanks again
