### ISSUE TITLE
Issue reading checkpoints back in

### ISSUE THREAD

**Issue by jhill1** [thetisproject/thetis#136]
Hi,

Ran a tidal model using 'dg-dg' and the 2D SWE. I saved the Velocity2D as h5 files, planning to do some post-processing afterwards.

The post processing code is:
```
...
V = VectorFunctionSpace(mesh, "DG", 1)
uv = Function(V, name='vel_2d')
print uv.dat.data.shape
for i in range(start_file,int(t_end/t_export)+1):
    print('Reading h5 files. Time ',i,i*t_export)
    checkpoint_file = DumbCheckpoint(file_location + '/Velocity2d_{:05}'.format(i),    mode=FILE_READ)
    checkpoint_file.load(uv)
    checkpoint_file.close()
```
The model was run on 10 cores, so running my post-processing code on 10 cores also, I get:
```
Reading Velocity h5 files. Time  10 9000
(163497, 2)
Reading Velocity h5 files. Time  10 9000
Traceback (most recent call last):
  File "post_processing_vel.py", line 56, in <module>
    checkpoint_file.load(uv)
  File "/home/firedrake/src/firedrake/firedrake/checkpointing.py", line 238, in load
    self.vwr.popGroup()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/firedrake/src/PyOP2/pyop2/petsc_base.py", line 347, in vec_context
    yield self._vec
  File "/home/firedrake/src/firedrake/firedrake/checkpointing.py", line 236, in load
    v.load(self.vwr)
  File "PETSc/Vec.pyx", line 445, in petsc4py.PETSc.Vec.load
petsc4py.PETSc.Error: error code 76
[3] VecLoad() line 931 in /tmp/pip-req-build-udnn6xhw/src/vec/vec/interface/vector.c
[3] VecLoad_Default() line 404 in /tmp/pip-req-build-udnn6xhw/src/vec/vec/utils/vecio.c
[3] VecLoad_HDF5() line 264 in /tmp/pip-req-build-udnn6xhw/src/vec/vec/utils/vecio.c
[3] Error in external library
[3] Error in HDF5 call H5Dopen2() Status -1
```
I'm assuming I've done something dumb and this is not a bug, but any help appreciated.

**Comment by zubba02** [comment]
#Probably not a very good solution (no 'firedrake' or 'thetis' functions are used), but do you think this resembles what is required to be achieved (if you have not already done, and not satisfied with this already). 

mesh = Mesh('runfiles/mesh.msh')
P1DG = FunctionSpace(mesh, "DG", 1)
uv_2d = Function(P1DG, name = 'vel_2d')

def magnitude (field, file):   
	with h5py.File('output/hdf5/'+ file, mode = 'r') as file:
		field = np.array(file['/fields/uv_2d/'])
		mag = [] 
		for i,xy in enumerate (field):
			mag.append(np.hypot(xy[0], xy[1]))
		return (np.array(mag))

uv_2d.dat.data[:] = magnitude(uv_2d, 'Velocity2d_00003.h5')
print (uv_2d.dat.data)

#plot uv_2d to confirm if uv_2d.dat.data has changed
outfile = File('x.pvd')
outfile.write(uv_2d)

**Comment by zubba02** [comment]
> Probably not a very good solution (no 'firedrake' or 'thetis' functions are used), but does this resemble what is required to be achieved. 

```python
mesh = Mesh('runfiles/mesh.msh')
P1DG = FunctionSpace(mesh, "DG", 1)
uv_2d = Function(P1DG, name = 'vel_2d')

def magnitude (field, file):   
	with h5py.File('output/hdf5/'+ file, mode = 'r') as file:
		field = np.array(file['/fields/uv_2d/'])
		mag = [] 
		for i,xy in enumerate (field):
			mag.append(np.hypot(xy[0], xy[1]))
		return (np.array(mag))

uv_2d.dat.data[:] = magnitude(uv_2d, 'Velocity2d_00003.h5')
print (uv_2d.dat.data)

#plot uv_2d to confirm if uv_2d.dat.data has changed
outfile = File('x.pvd')
outfile.write(uv_2d)

**Comment by wence-** [comment]
Because the checkpoint is time-dependent, you need to do `checkpoint_file.set_timestep(i*t_export, idx=i)` I think.

**Comment by jhill1** [comment]
Thanks both for the suggestions.

@wence- Didn't change anything. If I understand correctly, this set_timestep is if you save multiple timesteps to a checkpoint? Reading the elev field works fine in the above way (i.e. no timestep set).

@zubba02 I gave this a try and played around a wee bit, but just got the same value across the entire array or the decomposed array sizes didn't match those in the file (a factor of 10 out, shich at least makes sense). So this probably doesn't work with parallelisation. Can't run in serial as the Function wouldn't have halos and hence the number of items in the np.array would differ and even if I could figure that out, no idea what data would be in the halos.

Not sure what the issue is here (but glad I wasn't doing anything stupid ;-), but I think I'll make sure I add  any diagnostic fields at run time in future.

**Comment by wence-** [comment]
I think the bit of information that's missing is how you saved the files in the first place. I think Thetis dumps with timesteps even if you use separate files?

**Comment by jhill1** [comment]
Sneaky thetis. Files saved using the standard save to HDF5:
`options.fields_to_export_hdf5 = ['uv_2d', 'elev_2d']`

**Comment by tkarna** [comment]
An easy way to load the solution is to run the same script but instead of callin `solver_obj.assign_initial_conditions`, you do `solver_obj.load_state(my_export_index)`. You can then access the fields with the solver object e.g. `solver_obj.fields.uv_2d`.

Loading the data is handled in `HDF5Exporter.load`, where it reads
```
with DumbCheckpoint(filename, mode=FILE_READ, comm=function.comm) as f:
    f.load(function)
```
which is pretty much what you were trying to do. Did you remember to activate firedrake virtualenv?

**Comment by jhill1** [comment]
Thanks, @tkarna I'll give that a go tomorrow.

**Comment by jhill1** [comment]
For anyone else finding this, @tkarna suggestion worked: code is something like:

```
101 V = VectorFunctionSpace(mesh, "DG", 1)
102 uv = Function(V, name='vel_2d')
103 u_data_set = np.empty((t_n, uv.dat.data.shape[0]))
104 v_data_set = np.empty((t_n, uv.dat.data.shape[0]))
105 elev_data_set = np.empty((t_n, uv.dat.data.shape[0])) # elevation is also DG, so we can just do this.
106 count = 0
107 for i in range(start_file,int(t_end/t_export)+1):
108     print('Reading h5 files. Time ',i,i*t_export)
109     solverObj.load_state(i)
110     u_data_set[count, :] = solverObj.fields.uv_2d.dat.data[:,0]
111     v_data_set[count, :] = solverObj.fields.uv_2d.dat.data[:,1]
112     elev_data_set[count, :] = solverObj.fields.elev_2d.dat.data[:]
113     count += 1

```
which replaces everything in your model script including and after:
```
97 
98 solverObj.assign_initial_conditions(uv=Constant((1.0e-10,0.0)))
99 
```

**Comment by tkarna** [comment]
Good to know. In principle you should be able to read the files in without `solverObj` as well, just by mimicking what Thetis does under the hood.
