### ISSUE TITLE
Strong residuals

### ISSUE THREAD

**Issue by jwallwork23** [thetisproject/thetis#148]
In order to do dual weighted residual (DWR) error estimation in Thetis, we need strong residuals. In the (closed) PR [https://github.com/thetisproject/thetis/pull/146](url), I started working on this by defining strong residuals for each term in the shallow water and 2d tracer equations. However, the code structure needed some major changes. For error estimation, the idea was to use callbacks to periodically output strong residual fields, which are then weighted by adjoint solutions to give the DWR estimator.

The strong residual is also needed for SUPG stabilisation. Suppose we have the strong residual `R` for the steady tracer equation. Then SUPG amounts to adding a stabilisation term
`tau * dot(u, grad(psi)) * R * dx`
to the weak form, where `tau` is the stabilisation parameter, `u` is the fluid velocity and `psi` is the test function used. Instead of having a separate term for SUPG, perhaps it would make sense to simply add
`tau * dot(u, grad(psi)) * R_T * dx`
to the _weak_ residual in each term `T`, where `R_T` is the corresponding term in the _strong_ residual.

To do list:
- [ ] 2d SUPG
- [ ] 3d SUPG
- [x] Strong residuals for `tracer_eq_2d`.
- [ ] Strong residuals for `tracer_eq`.
- [x] Strong residuals for `shallowwater_eq`.
- [ ] Strong residuals for `momentum_eq`.
- [ ] Testing for these.
- [ ] Callbacks to output residual quantities as fields.

Also for DWR we need edge residuals to take into account fluxes:
- [ ] Edge residuals to implement SUPG in `tracer_eq_2d`.
- [ ] Edge residuals to implement SUPG in `tracer_eq`.
- [ ] Edge residuals for `shallowwater_eq`.
- [ ] Edge residuals for `momentum_eq`.
- [ ] Testing for these.

**Comment by tkarna** [comment]
Is there a small firedrake SUPG example (say, 2D advection) that would illustrate all the necessary bits? I guess the main difficulty here is to figure out a generic way how to express the strong residuals and the needed changes in the equation/time integrator classes. Something that would work for all 2D and 3D equations, and time integrators. Are we planning to support all spatial discretizations?

**Comment by jwallwork23** [comment]
The original reason we decided to consider SUPG was because of a tracer advection test case I considered with high diffusivity. I have re-implemented it in P1 space in Firedrake below:
```
from firedrake import *

nu = Constant(1e-1)  # diffusivity
dt = 0.1
Dt = Constant(dt)
n = 4

mesh = RectangleMesh(30 * n, 5 *n, 60, 10)
x, y = SpatialCoordinate(mesh)
P1 = FunctionSpace(mesh, "CG", 1)
velocity = Function(VectorFunctionSpace(mesh, "CG", 1)).interpolate(as_vector([1., 0.]))
u = Function(P1)
v = TestFunction(P1)

bell_x0 = 2.5
bell_y0 = 5.
bell_r0 = 0.457
bell = conditional(
    ge((1 + cos(pi * min_value(sqrt(pow(x - bell_x0, 2) + pow(y - bell_y0, 2)) / bell_r0, 1.0))), 0.),
    (1 + cos(pi * min_value(sqrt(pow(x - bell_x0, 2) + pow(y - bell_y0, 2)) / bell_r0, 1.0))),
    0.)
f = Function(P1).interpolate(0. + bell)  # Tracer source function
u0 = Function(P1)

u_mid = 0.5 * (u0 + u)  # Crank-Nicolson timestepping

# Weak form
F = v*(u - u0)*dx + Dt*(v*dot(velocity, grad(u_mid)) + nu*dot(grad(v), grad(u_mid)) -f*v)*dx

# Strong form
R = u - u0 + Dt*(dot(velocity, grad(u_mid)) - nu*div(grad(u_mid)) - f)

# SUPG stabilisation parameter
vnorm = sqrt(dot(velocity, velocity))
h = CellSize(mesh)
tau = h / (2.*vnorm)
#tau = pow(1/(0.5*Dt) + 2.0*vnorm/h + 4*nu/pow(h,2.0),-1)
F += tau*dot(velocity, grad(v))*R*dx

params = {'snes_type': 'newtonls',
          'ksp_type': 'gmres',
          'pc_type': 'sor',
         # 'snes_monitor': True,
         # 'ksp_monitor': True,
         }
bc = DirichletBC(P1, 0, 1)
prob = NonlinearVariationalProblem(F, u, bcs=bc)
solv = NonlinearVariationalSolver(prob, solver_parameters=params)

t = 0.
i = 0
T = 50.
outfile = File('plots/supg.pvd')
while (t < T):
    solv.solve()
    u0.assign(u)
    t += dt
    i += 1
    if (i % 20 == 0):
        print('t = {:.2f}'.format(t))
        outfile.write(u)
print('Norm(u) = {:.4e}'.format(norm(u)))
```
Yes, one of the issues I had when first sketching out a Thetis implementation for SUPG was that the stabilisation term is timestepper dependent. I guess turning the SUPG option on would mean changes being made to both the terms of the equation and also the timestepper. For example, in the above, the timestepper would need to add
```
tau * dot(velocity, grad(v)) * (u - u0) * dx,
```
whilst the (terms of the) tracer equation would need to add
```
tau * dot(velocity, grad(v)) * (dot(velocity, grad(u_mid)) - nu*div(grad(u_mid)) - f) * dx.
```
I suppose it would be convenient to store the stabilisation parameter `tau` as one of the `fields`.

I was planning to support all discretisations eventually, yes.
