### ISSUE TITLE
Vertical velocity solver is broken

### ISSUE THREAD

**Issue by tkarna** [thetisproject/thetis#153]
Vertical velocity solver appears to be broken. E.g. test `continuity3d/test_continuity_mes.py::test_setup1` fails.

There have been no related changes in Thetis recently so it's likely that this is a Firedrake bug.

**Comment by stephankramer** [comment]
Hm, so I was looking at this at well. And initially I was blaming the vertical velocity solver as well, but note that the `uv_3d` does not come out the same either (look at L2 error uv), whereas that should be just the result of a projection of a constant ufl expression. And indeed if I print out the values of uv_3d they come out as:
```
[[1.00829158 0.30248748 0.        ]
 [1.00829158 0.30248748 0.        ]
 [1.00825087 0.30247526 0.        ]
 ...
 [1.01373007 0.30411902 0.        ]
 [0.99114942 0.29734483 0.        ]
 [0.99114942 0.29734483 0.        ]]
```

**Comment by stephankramer** [comment]
So I suspect something to do with the recent supermesh merge?

**Comment by wence-** [comment]
I imagine the way I rewrote projection.py screwed something up?

**Comment by tkarna** [comment]
I see, it indeed looks like the projection is broken on a deformed mesh. Here's a MFE
```
from firedrake import *

mesh2d = RectangleMesh(4, 4, 15e3, 10e3)
n_layers = 4
mesh = ExtrudedMesh(mesh2d, n_layers, 1/n_layers)
mesh.coordinates.dat.data[:, 2] *= 1 + mesh.coordinates.dat.data[:, 0]

fs_v = VectorFunctionSpace(mesh, 'DG', 1)
uv_expr = as_vector([Constant(1.0), Constant(0.3), Constant(0)])
uv = Function(fs_v, name='uv').project(uv_expr)

l2_err_uv = errornorm(uv_expr, uv)/assemble(Constant(1.0, domain=mesh2d)*dx)
print('L2 error uv {:.6e}'.format(l2_err_uv))
assert l2_err_uv < 1e-15
```

**Comment by wence-** [comment]
Ufl change is merged. So hopefully this is fixed.

**Comment by tkarna** [comment]
Yes, all tests pass now.
