### ISSUE TITLE
AssertionError while trying to run Exmaple from thetis website

### ISSUE THREAD

**Issue by Qippu** [thetisproject/thetis#179]
Hear is the Code
##########################################
from thetis import *
mesh2d = RectangleMesh(20, 20, 10e3, 10e3)

fs_p1 = FunctionSpace(mesh2d, 'CG', 1)
bathymetry_2d = Function(fs_p1, name='Bathymetry').assign(10.0)

solver_obj = solver.FlowSolver(mesh2d, bathymetry_2d, n_layers=6)
options = solver_obj.options
options.element_family = 'dg-dg'
options.polynomial_degree = 1
options.timestepper_type = 'SSPRK22'
options.timestepper_options.use_automatic_timestep = False
options.solve_salinity = False
options.solve_temperature = False
options.simulation_export_time = 50.0
options.simulation_end_time = 3600.
options.timestep = 25.0

solver_obj.create_function_spaces()
init_elev = Function(solver_obj.function_spaces.H_2d)
coords = SpatialCoordinate(mesh2d)
init_elev.project(2.0*exp(-((coords[0] - 4e3)**2 + (coords[1] - 4.5e3)**2)/2.2e3**2))
solver_obj.assign_initial_conditions(elev=init_elev)

solver_obj.iterate()
###########################################

the output
What am I doing Wrong
##########################################
/home/qismath/firedrake/lib/python3.6/site-packages/pyproj/crs.py:77: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))
UFL:WARNING Discontinuous Lagrange element requested on triangle * interval, creating DQ element.
Coupled time integrator: CoupledTwoStageRK
  2D time integrator: ESDIRKTrapezoid
  3D time integrator: SSPRK22ALE
  3D implicit time integrator: BackwardEuler
Traceback (most recent call last):
  File "test_flow.py", line 23, in <module>
    solver_obj.assign_initial_conditions(elev=init_elev)
  File "/home/qismath/firedrake/src/thetis/thetis/solver.py", line 877, in assign_initial_conditions
    self.create_equations()
  File "/home/qismath/firedrake/src/thetis/thetis/solver.py", line 800, in create_equations
    elem_height=self.fields.v_elem_size_2d)
  File "/home/qismath/firedrake/src/thetis/thetis/utility.py", line 950, in __init__
    assert (len(nodes) == out_nodes)
AssertionError

**Comment by Qippu** [comment]
Exactly same thing happened when i tried to run 3D tidal channel demo from thetis website
https://thetisproject.org/demos/demo_3d_channel.py.html

**Comment by tkarna** [comment]
Thanks for reporting this. This is a known issue, see issue #177 and pull request #178. If you use the `equispaced-fs` branch, things should work. I hope we can merge the fix soon.

**Comment by Qippu** [comment]
how to do that exactly. I am new to github. i tried to chnage the solve.py in thetics directory, but the changes are not detected

**Comment by Qippu** [comment]
It works. But what is the meaning of this part

FutureWarning: '+init=:' syntax is deprecated. ':' is the preferred initialization method. return _prepare_from_string(" ".join(pjargs)) UFL:WARNING

**Comment by tkarna** [comment]
That warning originates from pyproj, you can ignore it.

**Comment by tkarna** [comment]
We've now merged the fix to master. You can update your thetis installation with:
```
git checkout master
git pull
```
