### ISSUE TITLE
Zenodo release request

### ISSUE THREAD

**Issue by swarder** [thetisproject/thetis#182]
Is it still the case that Zenodo requests are done manually for Thetis?

I'd like a Zenodo release for commit "424173012fbb6f60a85f544c560a18a061d5a5cb"

Thanks,

Simon

**Comment by wence-** [comment]
https://zenodo.org/record/3635721

**Comment by swarder** [comment]
Hello,

Could I please get an identical release for a different paper title?

The title is "A comparison of Bayesian inference and gradient-based approaches for friction parameter estimation"

Thanks very much

**Comment by tkarna** [comment]
Done, see https://doi.org/10.5281/zenodo.3698611

**Comment by swarder** [comment]
Thanks a lot!
