### ISSUE TITLE
Negative tracer values

### ISSUE THREAD

**Issue by jwallwork23** [thetisproject/thetis#188]
Apparently a few people are looking for a steady state passive tracer example in Thetis. So I thought I would code up the TELEMAC-2D 'point discharge with diffusion' test case which I considered using a standalone SUPG P1 solver in this paper: https://zenodo.org/record/3653373#.Xlkdaumnw5k

I made the new branch `passive-tracer-example`, where there is a coupled `'SteadyState'` solver. If I run `examples/passiveTracer/passiveTracer.py`, it gives a very encouraging plot:

![negative_tracer](https://user-images.githubusercontent.com/22053413/75554574-84bc0280-5a32-11ea-9413-25bef7f6acff.png)

Visually, it agrees nicely with the asymptotic solution and SUPG approximation as plotted in the paper (Figure 1, p.92). However, the values are significantly negative! Does anyone have an idea what is going wrong?

**Comment by tkarna** [comment]
Hmm, no idea. Is the (elevation, velocity) solution correct? One way to debug is to run the time dependent solution and make sure it works correctly.

**Comment by tkarna** [comment]
@jwallwork23 is this issue still active/relevant?

**Comment by jwallwork23** [comment]
Thanks for the reminder @tkarna! I just merged master into the branch and the negative tracer values have miraculously gone away (to order 1e-07).

![fixed](https://user-images.githubusercontent.com/22053413/105686851-a4cc9e00-5eef-11eb-8e63-2a4022106e6b.png)

I'll clean up the branch and make a PR to enable the coupled 2D steady state solver (which currently gets a `NotImplementedError`) because it isn't tested.
