### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by wence-** [thetisproject/thetis#19]
How about the below as a temporary logo?
<img width="612" alt="screen shot 2016-02-17 at 10 43 43" src="https://cloud.githubusercontent.com/assets/1126981/13107041/7d42918e-d563-11e5-8430-9c18fd3e2d26.png">

**Comment by dham** [comment]
Yes!

**Comment by tkarna** [comment]
Works for me

**Comment by wence-** [comment]
I've set this as the image for the thetisproject avatar, that's all for now.
