### ISSUE TITLE
New version of traitlets package

### ISSUE THREAD

**Issue by mc4117** [thetisproject/thetis#223]
The new version of the python package traitlets (5.0.4) does not contain the object ObserveHandler and hence `import thetis` fails because 'ObserveHandler' in "thetis/configuration.py", line 334 is not defined. 

Note: with the older version of traitlets (4.3.3) this error does not occur.

**Comment by tkarna** [comment]
I've reinstalled firedrake on Ubuntu 18.04 and could not reproduce this issue: I still have traitlets version 4.3.3. Thus we plausible need to support both the new and old API.
