### ISSUE TITLE
SW adjoint solver

### ISSUE THREAD

**Issue by jwallwork23** [thetisproject/thetis#235]
In my PhD I've been doing comparisons between continuous and discrete adjoint methods. I coded a continuous adjoint for the shallow water equations, which I use in my own solver framework. I've pushed it to Thetis on branch `continuous-adj-swe`.

If this is something that would be useful to Thetis users then we should have a discussion about how it would get hooked up in Thetis. For example, should the continuous adjoint get its own solver object or should it be attached to the forward one?

I could do the same for 2D tracers, too, if requested. If no one needs this functionality and pyadjoint/dolfin-adjoint is already more than  sufficient, then I'm also happy to just leave this code in my own repo!

**Comment by tkarna** [comment]
I'm inclined to consider this from application perspective. If the continuous adjoint solves a range of problems that users need to tackle, then incorporating it in Thetis is well justified. We can discuss this in the next meeting as well.

**Comment by jwallwork23** [comment]
Okay cool. I've added it to the [agenda](https://github.com/thetisproject/thetis/wiki/Thetis-meeting-agenda-2021-03-05).

**Comment by jwallwork23** [comment]
Closing due to a couple of errors in the formulation.
