### ISSUE TITLE
Viz output

### ISSUE THREAD

**Issue by wence-** [thetisproject/thetis#24]
The new firedrake viz output format supports multiple fields in the same file (they are all interpolated/projected into the same space).  I note that at the moment each field is dumped in its own file.  This is partly because that's all that's supported for viz up to now.  Is it better to put everything in one file?

**Comment by wence-** [comment]
I note as well that thetis always visualises in continuous spaces (even when the function to be output is discontinuous).  The new interpolation/projection auto-management in File objects always sends fields to the smallest space that "contains" them.  i.e. partially and/or fully discontinuous spaces are interpolated into a piecewise linear discontinuous space (rather than a piecewise linear continuous space).  This could also be made an option of the File object if it makes sense to want to always go to a piecewise continuous space for viz purposes.

**Comment by wence-** [comment]
The new API is described here http://firedrakeproject.org/visualisation.html

**Comment by tkarna** [comment]
> Is it better to put everything in one file?

Good question. Having only one file would be much cleaner, but based on my experience it is useful to store fields in separate files, especially in large simulations. You can then sync/backup etc only the fields/time steps that you need and not the whole thing.

**Comment by wence-** [comment]
So let me clarify. The setup is still as before. You get a pvd, that references one pvtu per `write` call. And you get one vtu per process per pvtu. The only change is that you can now have more than one field in each vtu. Now, one can extract single fields from the vtu using the python vtk bindings, but I have not written code to do so.

**Comment by tkarna** [comment]
Yes, I see that. It's just that for very large simulations extracting a field from a .vtu file is not a trivial task. That said, for very large simulations vtk is also not the appropriate output format.

Another aspect is that for visualization purposes it is useful to see the original function space, to the extent possible. That would also favor separate files as fields may belong to different spaces. So I'm leaning towards having a separate pvd file for each field, but I'm not feeling strongly about it.

**Comment by tkarna** [comment]
Anyway, thanks for changing the visualization API, I think it's much cleaner now. Yes, I think we can remove the hardcoded mapping to specific visualization spaces now. Thus far I've manually projected outputs to P1 prior to exporting because exporting discontinuous fields caused some issues, e.g. it involved a `Function.project`call which creates a new solver and slows things down. But as stated earlier, visualizing the original dg field is very useful. I'll try out the new API and see how it goes.

**Comment by tkarna** [comment]
As a side note, what are the missing pieces before we can deprecate the VTK output format and switch to hdf5? Hdf5 visualization support? Upgrading `DumbCheckpoint` to one that can handle different number of processes?

**Comment by wence-** [comment]
So there are two aspects. We need to dump the data in hdf5 and then write the appropriate xdmf. This, afaict doesn't buy us enough at the moment to move away from vtu for output, since it's nonzero effort. Even with hdf5, viz still only supports point evaluation spaces, so we still have to decimate somehow.

**Comment by tkarna** [comment]
Understood, makes sense.

**Comment by tkarna** [comment]
See pr #27

**Comment by stephankramer** [comment]
Great. Really good to have discontinuous output, in particular for debugging purposes. It would be good to have a continuous option as well, as the difference in file size is considerable (especially in 3D) - no preference as to what the default should be. I personally slightly prefer multiple fields per pvtu (just slightly easier in paraview), but don't care too much either way.

**Comment by tkarna** [comment]
Would it be sufficient to have a global "export_continuous" option, defaulting to False?

**Comment by tkarna** [comment]
If multiple fields were stored in the same *vtu file, would we just have a single `outputs/fields.pvd` and dump all the fields there? Or is there any reason to split fields to multiple files?

**Comment by tkarna** [comment]
Note that in order to easily fire up paraview, I normally save the state and then use the script `visualize-output.py outputs_dir mystate.pvsm`. It's a bit hacky though as it tries to replace the directory path in a naive way which is error prone. Also the `*.pvd` files are often empty (if simulation crashed etc) so it tries to generate a sane pvd file. Anyway setting up a meaningful visualization is nonzero task so we should find a good solution for this.

**Comment by wence-** [comment]
Pvd files at least should no longer ever be empty or corrupted

**Comment by stephankramer** [comment]
Note that the current exporter is now broken with firedrake master since `File(...) << (function, time_stamp)` is no longer supported. Does `File(...).write(function, time=time_stamp)` give the same functionality?

**Comment by wence-** [comment]
Yes

**Comment by tkarna** [comment]
Yes, I'll merge the current pr #27 to fix master.

**Comment by wence-** [comment]
Current state is sort of fixed
