### ISSUE TITLE
forcing.py, name 'PETSc' is not defined

### ISSUE THREAD

**Issue by MaihgrUmosch** [thetisproject/thetis#289]
Received this error when trying to use the thetis.forcing module in the example Columbia Plume.
`
> Exception has occurred: NameError
> name 'PETSc' is not defined

 > File "/home/.../firedrake/src/thetis/thetis/forcing.py", line 85, in ATMNetCDFTime
 
            @PETSc.Log.EventDecorator("thetis.ATMNetCDFTime.__init__")

  > File "/home/.../firedrake/src/thetis/thetis/forcing.py", line 81, in <module>
  
             class ATMNetCDFTime(interpolation.NetCDFTimeParser):

  > File "/home/.../firedrake/src/thetis/examples/columbia_plume/atm_forcing.py", line 13, in <module>
  
             from thetis.forcing import *
`

**Comment by tkarna** [comment]
Thanks for reporting this. I think this is already fixed in the current master branch, in commit 2043232. If you pull the latest Thetis master it should work.

**Comment by MaihgrUmosch** [comment]
I ran `firedrake-update --install thetis` and that stopped the previous error.

Still there is a problem associated with Petsc

> Exception has occurred: Error
> error code 65
> [0] PetscViewerFileSetName() at /home/<>/firedrake/src/petsc/src/sys/classes/viewer/impls/ascii/filev.c:649
> [0] PetscViewerFileSetName_ASCII() at /home/<>/firedrake/src/petsc/src/sys/classes/viewer/impls/ascii/filev.c:753
> [0] Unable to open file
> [0] Cannot open PetscViewer file: mesh_cre-plume_03_normal.msh
> File "/home/<>/firedrake/src/firedrake/firedrake/mesh.py", line 218, in _from_gmsh

           gmsh_viewer.setFileName(filename)

> File "/home/<>/firedrake/src/firedrake/firedrake/mesh.py", line 1799, in Mesh

           plex = _from_gmsh(meshfile, comm)

> File "/home/<>/firedrake/src/thetis/examples/columbia_plume/tidal_forcing.py", line 9, in test

           mesh2d = Mesh('mesh_cre-plume_02_normal.msh')

> File "/home/<>/firedrake/src/thetis/examples/columbia_plume/tidal_forcing.py", line 42, in <module>

           test()

**Comment by tkarna** [comment]
```
[0] Unable to open file
[0] Cannot open PetscViewer file: mesh_cre-plume_03_normal.msh
```
I think it just cannot find the mesh file. It should be in the repository though.

Note however that this is not a fully functional example as the Thetis repository does not include any of the forcing files. At least you'll hit errors with the atmospheric forcing files, e.g.
```
No files found: forcings/atm/nam/nam_air.local.2006_*_*.nc
```

**Comment by tkarna** [comment]
We cannot share the forcing files publicly due to copyright issues. If you however want to test the setup, send me an email and we'll see if we can share the data with you.

**Comment by MaihgrUmosch** [comment]
I ought to close this now as the original issue is resolved. The mesh is present in the repository, I don't know why it isn't accessible. Thank you for your help.
