### ISSUE TITLE
grid_tpxo9.nc download link error

### ISSUE THREAD

**Issue by MaihgrUmosch** [thetisproject/thetis#293]
Please could I have some help with getting the netcdf tidal forcing files?

There is a link in an error thrown in forcing.py to download grid_tpxo9.nc but I can't get it to work.

ftp://ftp.oce.orst.edu/dist/tides/Global/tpxo9_netcdf.tar.gz

![image](https://user-images.githubusercontent.com/32267184/152122327-785e38a1-0410-42f2-a51a-497362a25e5c.png)

**Comment by tkarna** [comment]
Thanks for reporting this, the download link is indeed obsolete. To get TPXO model data, you'll need to register on their website https://www.tpxo.net/global/tpxo9-atlas after which you'll receive a download link.

TPXO data format (e.g. variable and file names) has changed a little as well, so `TPXOTidalBoundaryForcing` will need to be adjusted a little. This update is on my list.

**Comment by MaihgrUmosch** [comment]
OK
