### ISSUE TITLE
NameError: name 'RectangleMesh' is not defined

### ISSUE THREAD

**Issue by Sijbrandb** [thetisproject/thetis#318]
Hi,

I am new at Thetis and was trying to run the examples. I did manage to fix the error: "NameError: name 'RectangleMesh' is not defined" once, but not sure what the solution was anymore. Could someone help me out with this one?

Best regards,
Sijbrand

**Comment by tkarna** [comment]
Could you please share a minimal piece of code that generates the error?

**Comment by Sijbrandb** [comment]
![afbeelding](https://user-images.githubusercontent.com/105936499/169652648-8b8e1a5b-f902-418d-a042-462ed29aafbe.png)

**Comment by tkarna** [comment]
That shouldn't be possible. Have you activated the Firedrake virtualenv?

**Comment by Sijbrandb** [comment]
yes even when the virtualenv has been activated the problem occurs.

**Comment by jwallwork23** [comment]
Did the Firedrake install terminate successfully? Please could you attach the `firedrake-install.log` file?

**Comment by Sijbrandb** [comment]
I think it did yes. [firedrake-install.log](https://github.com/thetisproject/thetis/files/8752728/firedrake-install.log)

**Comment by jwallwork23** [comment]
Thank you for providing the log. Looking at it, it appears that the install was unsuccessful. There were problems installing mpi4py and possibly also cython. I have asked the Firedrake development team if they know how to fix the issue and will get back to you.

**Comment by JDBetteridge** [comment]
You appear to be installing inside a virtual machine, how much memory did you give it?
By the looks of things the compiler was terminated (but no reason given):
`gcc: fatal error: Killed signal terminated program cc1`

One reason this would happen is there is not enough available RAM.
