### ISSUE TITLE
tohoku bathymetry checkpoint needs updating

### ISSUE THREAD

**Issue by stephankramer** [thetisproject/thetis#331]
As discussed on slack - due to a change in UFL, firedrake (some?) checkpoint files from before some date have stopped working. This currently breaks the tohoku inversion example. Regardless of whether or not this needs fixing in firedrake (say to prevent it from happening in the future) - for now we should just regenerate the checkpoint in that example (japan_sea_bathymetry.h5). @jwallwork23 - would you be able to do this? Maybe you can just commit straight to the fix-assigns branch (see #330) so we can get the build green again.

**Comment by jwallwork23** [comment]
Sure, will do.
