### ISSUE TITLE
Using other than CAT1 to control HobbyPCB Amps Band Switching

### ISSUE THREAD

**Issue by devmrs** [thetisproject/thetis#367]
Please ignore. Wrong Thetis group.

**Comment by devmrs** [comment]
I downloaded Serial Port Splitter from fabulatech.com. It allows a virtual serial port to talk to 2 different devices. I put Virtual Port COM1 in Cat 1 Control. Now COM1 sends commands to both COM3 (Hardrock-500) and to COM5 (Hardrock-50). Cost was $139. 
![image](https://github.com/thetisproject/thetis/assets/39437673/0bd01cf0-3468-42ef-8c16-6354f5596af0)

**Comment by stephankramer** [comment]
I think you may be a little lost here. This is the repository for the _ocean model_ Thetis (computer simulation). I see you've previously submitted issues in https://github.com/ramdor/Thetis Is that where you meant submit?

**Comment by devmrs** [comment]
Oops, wrong Thetis. Sorry
