### ISSUE TITLE
sspimex broken with swe

### ISSUE THREAD

**Issue by stephankramer** [thetisproject/thetis#48]
After changes to timeintegrators and swe equations+terms the channel2d test no longer works. Fixes to update the calls to new API are in fix-swe-sspimex branch but the example still blows up during the run.

**Comment by tkarna** [comment]
Thanks. This is not surprising as the example generates a shockwave which may blow up if there's no dissipation. I'll go through the examples in the next week or so and add come CI tests. Meanwhile the fix-swe-sspimex branch could be merged.

**Comment by tkarna** [comment]
This was just too long time step issue, fixed in #56 I believe.

**Comment by tkarna** [comment]
This is now fixed in #70 and #82.
