### ISSUE TITLE
test_adjoint fails in travis

### ISSUE THREAD

**Issue by tkarna** [thetisproject/thetis#59]
In current master `test_adjoint` doesn't pass travis tests. I tried re-running a couple of earlier commits that used to be green but they fail now:
https://travis-ci.org/thetisproject/thetis/builds/143139296

Any idea what's going on? Out of memory? Doesn't seem to run out of time.
I think I did blow the caches on travis recently so that could be a part of the reason.

**Comment by wence-** [comment]
No idea.  I've just blown the caches and restarted that job to see if anything changes...

**Comment by wence-** [comment]
I think I found a bug.  Maybe it will now work again.

**Comment by tkarna** [comment]
Thanks, restarted tests for some old commits and they indeed seem to be green again:
https://travis-ci.org/thetisproject/thetis/builds/143139296
https://travis-ci.org/thetisproject/thetis/builds/144525260
