### ISSUE TITLE
Jenkins issues

### ISSUE THREAD

**Issue by tkarna** [thetisproject/thetis#75]
These look like OS failures:
https://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis/58
https://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis/59

In addition, login button doesn't seem to work - I cannot stop/restart builds.

**Comment by wence-** [comment]
Hmmm.  Once you've logged in via github, you need to grant appropriate organisation access, I think:

https://github.com/settings/connections/applications/

**Comment by wence-** [comment]
Don't know what's going on with the failure.

**Comment by tkarna** [comment]
So if I revoke the access and then try to re-authorize it via the Login link in Jenkins, github throws me an error:

```
Reauthorization required
This application has made an unusually high number of requests to access your account. Please reauthorize the application to continue.
```

Firedrake Drone CI is in the list of authorized applications but that error keeps showing up.

**Comment by wence-** [comment]
Hmph, I've got nothing...

**Comment by wence-** [comment]
The failure is a COFFEE bug coneoproject/COFFEE#110.  We're not seeing it on Travis because the cached environment is older.  Drone doesn't cache things, so we always have up-to-date everything.

**Comment by tkarna** [comment]
Ah that makes sense.

**Comment by tkarna** [comment]
I'm still seeing these PETSc build failures...
https://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis/79
Any idea what's going on?

**Comment by wence-** [comment]
Ah, this is the problem with PETSc's build system having a race condition running in parallel.  I'll push the same fix that we use for firedrake.

**Comment by tkarna** [comment]
OK, nice.

**Comment by tkarna** [comment]
I think this is a new one
https://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis/94

**Comment by wence-** [comment]
Disk issues? @tmbgreaves

**Comment by tmbgreaves** [comment]
That looks like a container has got lost between the build and the subsequent viewing; my guess would be that the docker-gc cleanup script has been over-zealous in tidying what it thinks are unused volumes.
