### ISSUE TITLE
element_continuity wrong

### ISSUE THREAD

**Issue by wence-** [thetisproject/thetis#89]
In updating to the new Firedrake api (finat, not fiat elements).  I fixed `element_continuity`.  In doing so, I realised that there was a bug in its definition.

```python
def element_continuity(fiat_element):
    """Return an :class:`ElementContinuity` instance with the
    continuity of a given element.

    :arg fiat_element: The fiat element to determine the continuity
        of.
    :returns: A new :class:`ElementContinuity` instance.
    """
    import FIAT
    cell = fiat_element.get_reference_element()
...
        edofs = fiat_element.entity_dofs()
        dim = cell.get_spatial_dimension()
        dg = True
        for i in range(dim - 1):
            if any(len(k) for k in edofs[i].values()):
                dg = False
                break
        return ElementContinuity(dg, dg, dg)
```

This incorrectly reports elements with edge dofs, but not vertex dofs as dg (oops!).

Fixing this, leads to a bunch of tests failing.  So I wonder what's gone wrong.  (this fix is to loop:

`for i in range(dim)`, not `for i in range(dim-1)`.

The `api-changes` branch does this using the new finat elements.  But fails tests because it's not bug-for-bug compatible.

**Comment by tkarna** [comment]
This is now fixed in #88.
